### ISSUE TITLE
Bug: isn't working with scroll-snap-type: x mandatory

### ISSUE THREAD

**Issue by rbalet** [k3nsei/ng-in-viewport#1417]
## Description
The `inViewportAction` isn't triggered correctly when inside an `scroll-snap-type: x mandatory`.

## Reproduction
1. I've created a  [Stackblitz](https://stackblitz.com/edit/ng-in-viewport-example-2snt57?file=src%2Fpage-highlighting%2Fpage-highlighting.component.html) base on the demo

2. Horizontal slide to the nr.2 and he will stay gray,  
3. goes to the 3 and it will be green

## Code
```html
<div class="outer-container">
  <div class="inner-container" cols="2" rowHeight="2:1">
    <ng-container
      *ngFor="let item of items; let ind = index; trackBy: trackByItem">
      <div
        class="element"
        [class.active]="ind === activeIndex"
        inViewport
        [inViewportOptions]="{ threshold: [0], direction: 'horizontal' }"
        (inViewportAction)="highlight($event?.visible, ind)">
        {{ item.value }}
      </div>
    </ng-container>
  </div>
</div>
```

```scss
.outer-container {
  height: 100%;
  width: 100%;
  display: flex;
  align-items: center;
  .inner-container {
    white-space: nowrap;
    overflow: auto;
    scroll-snap-type: x mandatory;
    min-width: 100%;
    .element {
      scroll-snap-align: start;
      display: inline-block;
      width: 100%;
      height: 120px;
      background-color: rgb(158, 158, 158);
      font-size: 2em;
      font-weight: bold;
      color: rgba(255, 255, 255, 0.87);
      transition: background-color 0.25s ease-in, color 0.25s ease-in;

      &.active {
        background-color: #00c853;
        color: rgba(255, 255, 255, 0.87);
      }
    }
  }
}
```
```typescript
import { NgForOf } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Renderer2,
  inject,
} from '@angular/core';
import { MatGridListModule } from '@angular/material/grid-list';

import { InViewportAction, InViewportDirective } from 'ng-in-viewport';

interface HighlightingItem {
  id: string;
  value: number;
}

@Component({
  standalone: true,
  selector: 'invp-ex-page-highlighting',
  templateUrl: './page-highlighting.component.html',
  styleUrls: ['./page-highlighting.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgForOf, MatGridListModule, InViewportDirective],
})
export class PageHighlightingComponent {
  activeIndex = 0;
  public readonly items: HighlightingItem[] = Array.from(
    { length: 100 },
    (_, i) => ({
      id: crypto.randomUUID(),
      value: i + 1,
    })
  );

  public highlight(isVisible: boolean, index: number): void {
    if (isVisible) this.activeIndex = index;
  }

  public trackByItem(index: number, { id }: HighlightingItem): string {
    return id;
  }
}

export default PageHighlightingComponent;
```

## Workaround
Adding `threshold: [-10]` kind of help but not all the time

## Analyse
It seems like the InViewportAction is triggered not at the same time as the browser is doing his magic.

## Idea
We could add an input where we should recheck if the element is actually in the viewport cause we know the animation will take approximatively 1sec.
